src/apex/force/main/default/objects/DeliveryPlan__c/DeliveryPlan__c.object-meta.xml
<CustomObject>
	<label>Delivery Plan</label>
	<nameField>
		<displayFormat>Delivery Plan {0}</displayFormat>
		<label>Delivery Plan Name</label>
		<type>AutoNumber</type>
		<startingNumber>1</startingNumber>
	</nameField>
	<pluralLabel>Delivery Plans</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <label>Delivery Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force-app/main/default/objects/DeliveryRoute__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Delivery_Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/DeliveryRoute__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>Delivery_Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/DeliveryWaypoint__c/DeliveryWaypoint__c.object-meta.xml
<CustomObject>
    <label>Delivery Waypoint</label>
    <nameField>
        <label>Delivery Waypoint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Waypoints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force-app/main/default/objects/DeliveryWaypoint__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route</label>
    <referenceTo>DeliveryRoute__c</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>Delivery_Waypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/DeliveryWaypoint__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>DeliveryWaypoints</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/apex/force/main/default/objects/DeliveryWaypoint__c/fields/WaypointNumber__c.field-meta.xml
<CustomField>
    <fullName>WaypointNumber__c</fullName>
    <label>Waypoint Number</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/apex/force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
	<label>Vehicle</label>
	<nameField>
		<label>Vehicle Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Vehicles</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/Vehicle__c/fields/VehicleType__c.field-meta.xml
<CustomField>
	<fullName>VehicleType__c</fullName>
	<deleteConstraint>Restrict</deleteConstraint>
	<label>Vehicle Type</label>
	<referenceTo>VehicleType__c</referenceTo>
	<relationshipLabel>Vehicles</relationshipLabel>
	<relationshipName>Vehicles</relationshipName>
	<required>true</required>
	<type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/Vehicle__c/fields/Warehouse__c.field-meta.xml
<CustomField>
	<fullName>Warehouse__c</fullName>
	<deleteConstraint>Restrict</deleteConstraint>
	<label>Warehouse</label>
	<referenceTo>Warehouse__c</referenceTo>
	<relationshipLabel>Vehicles</relationshipLabel>
	<relationshipName>Vehicles</relationshipName>
	<required>true</required>
	<type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/VehicleType__c/VehicleType__c.object-meta.xml
<CustomObject>
	<label>Vehicle Type</label>
	<nameField>
		<label>Vehicle Type Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Vehicle Types</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
	<label>Warehouse</label>
	<nameField>
		<label>Warehouse Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Warehouses</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/Warehouse__c/fields/Contact__c.field-meta.xml
<CustomField>
	<fullName>Contact__c</fullName>
	<deleteConstraint>Restrict</deleteConstraint>
	<label>Contact</label>
	<referenceTo>Contact</referenceTo>
	<relationshipLabel>Warehouses</relationshipLabel>
	<relationshipName>Warehouses</relationshipName>
	<required>true</required>
	<type>Lookup</type>
</CustomField>

src/apex/force/main/default/classes/RouteAPITest.cls
/**
 * Copyright (c) 2017-2018, FinancialForce.com, inc
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 * - Neither the name of the FinancialForce.com, inc nor the names of its contributors
 *      may be used to endorse or promote products derived from this software without
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

@isTest(seeAllData=false)
public class RouteAPITest {

	@isTest
	private static void saveRoutes_null_exception()
   	{
		// Given
		List<DeliveryRoute__c> routesToSave = null;

		// When
		try
		{
			List<DeliveryRoute__c> response = RouteAPI.saveRoutes(routesToSave);
			System.assert(false, 'Expected exception');
		}
		catch(Exception ex)
		{
		}
   	}

	@isTest
	private static void saveRoutes_inValidRoutes_exception()
    {   
		// Given
		List<DeliveryRoute__c> routesToSave = ceateRoutesToSave();

		routesToSave.get(1).DeliveryPlan__c = null;

		// When
		try
		{
			List<DeliveryRoute__c> response = RouteAPI.saveRoutes(routesToSave);
			System.assert(false, 'Expected exception');
		}
		catch(Exception ex)
		{
		}
    }

	@isTest
	private static void saveRoutes_validRoutes_Saves()
    {
	   	//Given
		List<DeliveryRoute__c> routesToSave = ceateRoutesToSave();

		//when
		List<DeliveryRoute__c> response = RouteAPI.saveRoutes(routesToSave);

		//Then
		assertEquals(routesToSave, response);
    }

	private static void assertEquals(List<DeliveryRoute__c> expected, List<DeliveryRoute__c> actual)
	{
		System.assertEquals(expected.size(), actual.size());

		for(Integer count = 0; count< expected.size(); count++)
		{
			assertEquals(expected.get(count), actual.get(count));
		}
	}

	private static void assertEquals(DeliveryRoute__c expected, DeliveryRoute__c actual)
	{
		System.assertEquals(expected.DeliveryPlan__c, actual.DeliveryPlan__c);
		System.assertEquals(expected.Driver__c, actual.Driver__c);
		System.assertEquals(expected.URL__c, actual.URL__c);
		System.assertEquals(expected.Vehicle__c, actual.Vehicle__c);
	}

	private static List<DeliveryRoute__c> ceateRoutesToSave()
	{
		Account account = new Account(Name='Account One');
		insert account;

        Contact contact = new Contact(FirstName = 'Contact', LastName = 'One', MailingLatitude = 1, MailingLongitude = 1);
		insert contact;
        
        Warehouse__c warehouse = new Warehouse__c(Contact__c = contact.Id);
		insert warehouse;
        
        VehicleType__c vtype = new VehicleType__c(name ='test');
		insert vtype;
        
        Vehicle__c vehicle = new Vehicle__c(VehicleType__c = vtype.id, Warehouse__c = warehouse.id);
        insert vehicle;

		DeliveryPlan__c plan = new DeliveryPlan__c();
		insert plan;
		
		List<DeliveryRoute__c> routes = new List<DeliveryRoute__c>();
		routes.add(new DeliveryRoute__c(DeliveryPlan__c = plan.Id, URL__c ='Test', Vehicle__c = vehicle.Id));
		routes.add(new DeliveryRoute__c(DeliveryPlan__c = plan.Id, URL__c ='Test', Vehicle__c = vehicle.Id));
		routes.add(new DeliveryRoute__c(DeliveryPlan__c = plan.Id, URL__c ='Test', Vehicle__c = vehicle.Id));

		return routes;

	/*	List<DeliveryWaypoint__c> waypoints = new List<DeliveryWaypoint__c>();
		for(Integer count = 0; count < 5; count++)
		{
			waypoints.add(new DeliveryWaypoint__c(DeliveryRoute__c = route.Id, Order__c = order.Id, WaypointNumber__c = count));
		}
		insert waypoints;*/
	}
}