src/apex/force/main/default/objects/DeliveryPlan__c/DeliveryPlan__c.object-meta.xml
<CustomObject>
	<label>Delivery Plan</label>
	<nameField>
		<displayFormat>Delivery Plan {0}</displayFormat>
		<label>Delivery Plan Name</label>
		<type>AutoNumber</type>
		<startingNumber>1</startingNumber>
	</nameField>
	<pluralLabel>Delivery Plans</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <label>Delivery Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force-app/main/default/objects/DeliveryRoute__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>Delivery_Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/DeliveryWaypoint__c/DeliveryWaypoint__c.object-meta.xml
<CustomObject>
    <label>Delivery Waypoint</label>
    <nameField>
        <label>Delivery Waypoint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Waypoints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force-app/main/default/objects/DeliveryWaypoint__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route</label>
    <referenceTo>DeliveryRoute__c</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>Delivery_Waypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/DeliveryWaypoint__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>DeliveryWaypoints</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/apex/force/main/default/objects/DeliveryWaypoint__c/fields/WaypointNumber__c.field-meta.xml
<CustomField>
    <fullName>WaypointNumber__c</fullName>
    <label>Waypoint Number</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/apex/force-app/main/default/objects/GenerateDataTask__c/GenerateDataTask__c.object-meta.xml
<CustomObject>
    <label>Generate Data Task</label>
    <nameField>
        <displayFormat>Generate Data Task {0}</displayFormat>
        <label>Generate Data Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generate Data Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
	<label>Vehicle</label>
	<nameField>
		<label>Vehicle Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Vehicles</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/Vehicle__c/fields/VehicleType__c.field-meta.xml
<CustomField>
	<fullName>VehicleType__c</fullName>
	<deleteConstraint>Restrict</deleteConstraint>
	<label>Vehicle Type</label>
	<referenceTo>VehicleType__c</referenceTo>
	<relationshipLabel>Vehicles</relationshipLabel>
	<relationshipName>Vehicles</relationshipName>
	<required>true</required>
	<type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/Vehicle__c/fields/Warehouse__c.field-meta.xml
<CustomField>
	<fullName>Warehouse__c</fullName>
	<deleteConstraint>Restrict</deleteConstraint>
	<label>Warehouse</label>
	<referenceTo>Warehouse__c</referenceTo>
	<relationshipLabel>Vehicles</relationshipLabel>
	<relationshipName>Vehicles</relationshipName>
	<required>true</required>
	<type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/VehicleType__c/VehicleType__c.object-meta.xml
<CustomObject>
	<label>Vehicle Type</label>
	<nameField>
		<label>Vehicle Type Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Vehicle Types</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
	<label>Warehouse</label>
	<nameField>
		<label>Warehouse Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Warehouses</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/Warehouse__c/fields/Contact__c.field-meta.xml
<CustomField>
	<fullName>Contact__c</fullName>
	<deleteConstraint>Restrict</deleteConstraint>
	<label>Contact</label>
	<referenceTo>Contact</referenceTo>
	<relationshipLabel>Warehouses</relationshipLabel>
	<relationshipName>Warehouses</relationshipName>
	<required>true</required>
	<type>Lookup</type>
</CustomField>

src/apex/force/main/default/classes/DataDeleterTest.cls
/**
 * Copyright (c) 2017-2018, FinancialForce.com, inc
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 * - Neither the name of the FinancialForce.com, inc nor the names of its contributors
 *      may be used to endorse or promote products derived from this software without
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **/

@isTest(SeeAllData=false)
private class DataDeleterTest
{
    @isTest
    static void deleteData_deletesData()
    {
        //Given
		insertData();
        
        //When
        DataDeleter.deleteData();
        
        //Then
        assertNoCreatedDataInOrg();
    }
    
    private static void insertData()
    {
		Account account = new Account(Name='Account One');
		insert account;

        Contact contact = new Contact(FirstName = 'Contact', LastName = 'One', MailingLatitude = 1, MailingLongitude = 1);
		insert contact;
        
        Warehouse__c warehouse = new Warehouse__c(Contact__c = contact.Id);
		insert warehouse;
        
        Order order = new Order(AccountId = account.Id, ShipToContactId = contact.Id, EffectiveDate = Date.newInstance(2017, 10, 1), Status = 'Draft');
        insert order;
        
        VehicleType__c vtype = new VehicleType__c(name ='test');
		insert vtype;
        
        Vehicle__c vehicle = new Vehicle__c(VehicleType__c = vtype.id, Warehouse__c = warehouse.id);
        insert vehicle;

		DeliveryPlan__c plan = new DeliveryPlan__c();
		insert plan;
		
		DeliveryRoute__c route = new DeliveryRoute__c(DeliveryPlan__c = plan.Id, Vehicle__c = vehicle.Id);
        insert route;

		DeliveryWaypoint__c waypoint = new DeliveryWaypoint__c(DeliveryRoute__c = route.Id, Order__c = order.Id, WaypointNumber__c = 1);
        insert waypoint;

		GenerateDataTask__c task = new GenerateDataTask__c();
		insert task;
    }
    
    private static void assertNoCreatedDataInOrg()
    {
        List<Vehicle__c> vehicles = (List<Vehicle__c>)[SELECT Id FROM Vehicle__c];
        List<VehicleType__c> types = (List<VehicleType__c>)[SELECT Id FROM VehicleType__c];
		List<DeliveryWaypoint__c> waypoints = (List<DeliveryWaypoint__c>)[SELECT Id FROM DeliveryWaypoint__c];
		List<DeliveryRoute__c> routes = (List<DeliveryRoute__c>)[SELECT Id FROM DeliveryRoute__c];
        List<DeliveryPlan__c> plans = (List<DeliveryPlan__c>)[SELECT Id FROM DeliveryPlan__c];
		List<Order> orders = (List<Order>)[SELECT Id FROM Order];
        List<Warehouse__c> warehouses = (List<Warehouse__c>)[SELECT Id FROM Warehouse__c];
        List<Contact> contact = (List<Contact>)[SELECT Id FROM Contact];
        List<Account> accounts = (List<Account>)[SELECT Id FROM Account];
		List<GenerateDataTask__c> tasks = (List<GenerateDataTask__c>)[SELECT Id FROM GenerateDataTask__c];

        System.assertEquals(0, vehicles.size());
        System.assertEquals(0, types.size());
		System.assertEquals(0, waypoints.size());
        System.assertEquals(0, routes.size());
		System.assertEquals(0, plans.size());
        System.assertEquals(0, orders.size());
        System.assertEquals(0, warehouses.size());
        System.assertEquals(0, contact.size());
		System.assertEquals(0, accounts.size());
		System.assertEquals(0, tasks.size());
    }
}