src/apex/force/main/default/objects/DeliveryRoute__c/DeliveryRoute__c.object-meta.xml
<CustomObject>
    <label>Delivery Route</label>
    <nameField>
        <label>Delivery Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force-app/main/default/objects/DeliveryRoute__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Delivery Routes</relationshipLabel>
    <relationshipName>Delivery_Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/DeliveryWaypoint__c/DeliveryWaypoint__c.object-meta.xml
<CustomObject>
    <label>Delivery Waypoint</label>
    <nameField>
        <label>Delivery Waypoint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Waypoints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force-app/main/default/objects/DeliveryWaypoint__c/fields/DeliveryRoute__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRoute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Route</label>
    <referenceTo>DeliveryRoute__c</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>Delivery_Waypoints</relationshipName>
    <type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/DeliveryWaypoint__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Delivery Waypoints</relationshipLabel>
    <relationshipName>DeliveryWaypoints</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/apex/force/main/default/objects/DeliveryWaypoint__c/fields/WaypointNumber__c.field-meta.xml
<CustomField>
    <fullName>WaypointNumber__c</fullName>
    <label>Waypoint Number</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/apex/force-app/main/default/objects/OrizuruSettings__c/OrizuruSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for the Orizuru Sample Application</description>
    <label>Orizuru Settings</label>
</CustomObject>

src/apex/force/main/default/objects/OrizuruSettings__c/fields/GoogleMapsApiKey__c.field-meta.xml
<CustomField>
    <fullName>GoogleMapsApiKey__c</fullName>
    <description>The API required to make calls to the Google Maps API</description>
    <label>Google Maps API Key</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/apex/force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
	<label>Vehicle</label>
	<nameField>
		<label>Vehicle Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Vehicles</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/Vehicle__c/fields/VehicleType__c.field-meta.xml
<CustomField>
	<fullName>VehicleType__c</fullName>
	<deleteConstraint>Restrict</deleteConstraint>
	<label>Vehicle Type</label>
	<referenceTo>VehicleType__c</referenceTo>
	<relationshipLabel>Vehicles</relationshipLabel>
	<relationshipName>Vehicles</relationshipName>
	<required>true</required>
	<type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/Vehicle__c/fields/Warehouse__c.field-meta.xml
<CustomField>
	<fullName>Warehouse__c</fullName>
	<deleteConstraint>Restrict</deleteConstraint>
	<label>Warehouse</label>
	<referenceTo>Warehouse__c</referenceTo>
	<relationshipLabel>Vehicles</relationshipLabel>
	<relationshipName>Vehicles</relationshipName>
	<required>true</required>
	<type>Lookup</type>
</CustomField>

src/apex/force-app/main/default/objects/VehicleType__c/VehicleType__c.object-meta.xml
<CustomObject>
	<label>Vehicle Type</label>
	<nameField>
		<label>Vehicle Type Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Vehicle Types</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
	<label>Warehouse</label>
	<nameField>
		<label>Warehouse Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>Warehouses</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/apex/force/main/default/objects/Warehouse__c/fields/Contact__c.field-meta.xml
<CustomField>
	<fullName>Contact__c</fullName>
	<deleteConstraint>Restrict</deleteConstraint>
	<label>Contact</label>
	<referenceTo>Contact</referenceTo>
	<relationshipLabel>Warehouses</relationshipLabel>
	<relationshipName>Warehouses</relationshipName>
	<required>true</required>
	<type>Lookup</type>
</CustomField>

src/apex/force/main/default/classes/DeliveryRouteServiceTest.cls
/**
 * Copyright (c) 2017, FinancialForce.com, inc
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 *   are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 * - Neither the name of the FinancialForce.com, inc nor the names of its contributors
 *      may be used to endorse or promote products derived from this software without
 *      specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 *  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 *  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 *  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 *  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 *  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 **/

@isTest(SeeAllData=false)
private class DeliveryRouteServiceTest
{
	@IsTest
	private static void generateUrl_shouldReturnTheUrl_whenThereIsADeliveryWaypoint()
	{
		//Given
		OrizuruSettings__c settings = new OrizuruSettings__c(GoogleMapsApiKey__c='testingApiKey');
		insert settings;

		String expected = 'https://www.google.com/maps/embed/v1/directions?key=' + settings.GoogleMapsApiKey__c + '&origin=5.000000000000000,5.000000000000000&destination=5.000000000000000,5.000000000000000&waypoints=1.000000000000000,1.000000000000000';
		
		Account account = new Account(Name = 'Account One');
		insert account;

		Contact[] contacts = new Contact[]{
			new Contact(FirstName = 'Contact', LastName = 'One', MailingLatitude = 1, MailingLongitude = 1),
			new Contact(FirstName = 'Contact', LastName = 'Two', MailingLatitude = 5, MailingLongitude = 5)
		};
		insert contacts;

		Warehouse__c warehouse = new Warehouse__c(Contact__c = contacts[1].Id);
		insert warehouse;

		VehicleType__c vehicleType = new VehicleType__c();
		insert vehicleType;

		Vehicle__c vehicle = new Vehicle__c(VehicleType__c = vehicleType.Id, Warehouse__c = warehouse.Id);
		insert vehicle;

		Order order = new Order(AccountId = account.Id, ShipToContactId = contacts[0].Id, EffectiveDate = Date.newInstance(2017, 10, 1), Status = 'Draft');
		insert order;

		DeliveryRoute__c deliveryRoute = new DeliveryRoute__c(Vehicle__c = vehicle.Id);
        insert deliveryRoute;

		DeliveryWaypoint__c waypoint = new DeliveryWaypoint__c(DeliveryRoute__c = deliveryRoute.Id, Order__c = order.Id, WaypointNumber__c = 1);
        insert waypoint;

		DeliveryRouteService service = DeliveryRouteService.newInstance();

		//When
		String actual = DeliveryRouteService.newInstance().generateUrl(deliveryRoute.Id);

		//Then
		System.assertEquals(expected, actual);
	}

	@IsTest
	private static void generateUrl_ShouldReturnTheUrl_WithMultipleDeliveries()
	{
		//Given
		OrizuruSettings__c settings = new OrizuruSettings__c(GoogleMapsApiKey__c='testingApiKey');
		insert settings;

		String expected = 'https://www.google.com/maps/embed/v1/directions?key=' + settings.GoogleMapsApiKey__c + '&origin=5.000000000000000,5.000000000000000&destination=5.000000000000000,5.000000000000000&waypoints=1.000000000000000,1.000000000000000|2.000000000000000,2.000000000000000|3.000000000000000,3.000000000000000';
		
		Account[] accounts = new Account[]{
			new Account(Name = 'Account One'),
			new Account(Name = 'Account Two'),
			new Account(Name = 'Account Three')
		};
		insert accounts;
		
		Contact[] contacts = new Contact[]{
			new Contact(FirstName = 'Contact', LastName = 'One', MailingLatitude = 1, MailingLongitude = 1),
			new Contact(FirstName = 'Contact', LastName = 'Two', MailingLatitude = 2, MailingLongitude = 2),
			new Contact(FirstName = 'Contact', LastName = 'Three', MailingLatitude = 3, MailingLongitude = 3),
			new Contact(FirstName = 'Contact', LastName = 'Four', MailingLatitude = 5, MailingLongitude = 5)
		};
		insert contacts;

		Warehouse__c warehouse = new Warehouse__c(Contact__c = contacts[3].Id);
		insert warehouse;

		VehicleType__c vehicleType = new VehicleType__c();
		insert vehicleType;

		Vehicle__c vehicle = new Vehicle__c(VehicleType__c = vehicleType.Id, Warehouse__c = warehouse.Id);
		insert vehicle;

		Order[] orders = new Order[]{
			new Order(AccountId = accounts[0].Id, ShipToContactId = contacts[0].Id, EffectiveDate = Date.newInstance(2017, 10, 1), Status = 'Draft'),
			new Order(AccountId = accounts[1].Id, ShipToContactId = contacts[1].Id, EffectiveDate = Date.newInstance(2017, 10, 1), Status = 'Draft'),
			new Order(AccountId = accounts[2].Id, ShipToContactId = contacts[2].Id, EffectiveDate = Date.newInstance(2017, 10, 1), Status = 'Draft')
		};
		insert orders;

		DeliveryRoute__c deliveryRoute = new DeliveryRoute__c(Vehicle__c = vehicle.Id);
        insert deliveryRoute;
		
		DeliveryWaypoint__c[] waypoints = new DeliveryWaypoint__c[]{
            new DeliveryWaypoint__c(DeliveryRoute__c = deliveryRoute.Id, Order__c = orders[0].Id, WaypointNumber__c = 1),
            new DeliveryWaypoint__c(DeliveryRoute__c = deliveryRoute.Id, Order__c = orders[1].Id, WaypointNumber__c = 2),
			new DeliveryWaypoint__c(DeliveryRoute__c = deliveryRoute.Id, Order__c = orders[2].Id, WaypointNumber__c = 3)
        };
        insert waypoints;

		DeliveryRouteService service = DeliveryRouteService.newInstance();

		//When
		String actual = DeliveryRouteService.newInstance().generateUrl(deliveryRoute.Id);

		//Then
		System.assertEquals(expected, actual);
	}
}